# Generated by Django 3.0 on 2019-12-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='hotels/photos'),
        ),
    ]
